 CREATE OR REPLACE VIEW RATING_OWNER.view_dim_toll_stage_closed AS
select   
s.TOLL_STAGE_ID, stage_code, stage_name
,dcc.CLOSED_CYCLE_ID, dcc.cycle_name
,s.toll_a as checkin_toll_id,ta.toll_name as checkin_toll_name
,s.toll_b as checkout_toll_id,tb.toll_name as checkout_toll_name
,start_date, end_date, s.status, s.status_commercial
,s.bot_a, s.bot_b, s.boo
FROM RATING_OWNER.TOLL_STAGE s
LEFT JOIN RATING_OWNER.TOLL ta ON ta.toll_id = s.toll_a
LEFT JOIN RATING_OWNER.TOLL tb ON tb.toll_id = s.toll_b
LEFT JOIN RATING_OWNER.CLOSED_CYCLE dcc ON dcc.CLOSED_CYCLE_ID = s.cycle_id
where s.STATUS = 1;


CREATE OR REPLACE PROCEDURE  RATING_OWNER.SP_GET_BACKEND3_VEHICLE_TRANS_REPORT_DETAIL (
    P_FROM_DATE  DATE,
    P_TO_DATE    DATE,
    P_CYCLE_NAME	   IN NVARCHAR(2000) DEFAULT NULL,
    P_RESULT           OUT SYS.TRANSPORT_CURSOR_TYPE.TRANSPORT_CURSOR
)
AS
    V_SQL      VARCHAR(32000);
    V_SORTING  VARCHAR(4000);
BEGIN

    V_SQL :=
    	'SELECT
		TO_NUMBER(TO_CHAR(B.CHECKOUT_DATETIME, ''YYYYMMDDHH24'')) DateTimeId
		,B.TRANSPORT_TRANS_ID, B.CHECKIN_DATETIME, B.CHECKOUT_DATETIME
		,B.PLATE, B.ETAG_NUMBER 
		, B.VEHICLE_TYPE 
		,CHECKIN_TOLL_NAME,CHECKOUT_TOLL_NAME,A.PRICE_TYPE
		,A.PRICE_TICKET_TYPE
		,B.CHARGE_STATUS
		,A.PRICE_AMOUNT 
		,A.PRICE_AMOUNT AS PRICE_AMOUNT_TAX
		,B.TOTAL_AMOUNT 
		,C.BOT_A AS BOT_IN
		,C.BOT_B AS BOT_OUT
		,C.CYCLE_NAME
		,NULL PRICE_BOT
		,''E'' SOURCE_TRANS
		,C.STAGE_NAME
		,C.BOO
		,NULL BOO_TYPE
		,CHECKIN_LANE_ID
		,CHECKOUT_LANE_ID
		FROM RATING_OWNER.TRANSPORT_TRANS_STAGE_DETAIL A
		INNER JOIN RATING_OWNER.TRANSPORT_TRANSACTION_STAGE B ON A.TRANSPORT_TRANS_ID = B.TRANSPORT_TRANS_ID 
		INNER JOIN RATING_OWNER.view_dim_toll_stage_closed C ON A.STAGE_ID = C.TOLL_STAGE_ID 
        WHERE T.CHECKOUT_DATETIME >= ''' || TO_CHAR(P_FROM_DATE) || '''
        AND T.CHECKOUT_DATETIME <= ''' || TO_CHAR(P_TO_DATE) || '''
	    AND ( ''' || P_CYCLE_NAME || '''  IS NULL OR COUT.CYCLE_NAME =  ''' || P_CYCLE_NAME || ''' )
        ';

    OPEN P_RESULT FOR V_SQL;
END;


CREATE OR REPLACE PROCEDURE  RATING_OWNER.SP_GET_BACKEND3_VEHICLE_TRANS_REPORT (
    P_FROM_DATE  DATE,
    P_TO_DATE    DATE,
    P_CYCLE_NAME	   IN NVARCHAR(2000) DEFAULT NULL,
    P_RESULT           OUT SYS.TRANSPORT_CURSOR_TYPE.TRANSPORT_CURSOR
)
AS
    V_SQL      VARCHAR(32000);
    V_SORTING  VARCHAR(4000);
BEGIN

    V_SQL :=
    	'SELECT
			A.PRICE_TYPE,A.PRICE_TICKET_TYPE,C.CHECKIN_TOLL_NAME,C.CHECKOUT_TOLL_NAME
			,C.STAGE_NAME
			,COUNT(DISTINCT TRANSPORT_TRANS_ID) QUANTITY  
			,999 BOT_PRICE_INCREASE, 999 BOT_AMOUNT_INCREASE
			,999 INTEROPERABLE_PRICE_INCREASE, 999 INTEROPERABLE_AMOUNT_INCREASE
			,99  INCREASE_ADJUSTMENT
			,999 BOT_AMOUNT_DECREASE, 999 INTEROPERABLE_AMOUNT_DECREASE
			,999 DECREASE
			,999 BOT_AMOUNT_TOTAL  -- BOT  Thành tiền tổng
			,999 INTEROPERABLE_AMOUNT_TOTAL -- Liên thông Thành tiền tổng
			,99 TOTAL
			,999 BOT_AMOUNT_TOTAL_ALL  -- BOT  Thành tiền tổng
			,999 INTEROPERABLE_AMOUNT_TOTAL_ALL -- Liên thông Thành tiền tổng
			FROM RATING_OWNER.TRANSPORT_TRANS_STAGE_DETAIL A
			INNER JOIN RATING_OWNER.view_dim_toll_stage_closed C ON A.STAGE_ID = C.TOLL_STAGE_ID 
			,C.STAGE_NAME
			        WHERE A.CHECKOUT_DATETIME >= ''' || TO_CHAR(P_FROM_DATE) || '''
			        AND A.CHECKOUT_DATETIME <= ''' || TO_CHAR(P_TO_DATE) || '''
				    AND ( ''' || P_CYCLE_NAME || '''  IS NULL OR C.CYCLE_NAME =  ''' || P_CYCLE_NAME || ''' )
			GROUP BY A.PRICE_TYPE,A.PRICE_TICKET_TYPE,C.CHECKIN_TOLL_NAME,C.CHECKOUT_TOLL_NAME
        ';

    OPEN P_RESULT FOR V_SQL;
END;