-- NEW SCRIPT IN ORCL.
-- DATE: MAR 17, 2026
-- TIME: 4:22:12 PM
TRUNCATE TABLE QLPN.THA_CO_DIEU_KIENS;

INSERT INTO QLPN.THA_CO_DIEU_KIENS (
    NGAY_XET,
    TINH_TRANG_ID,
    SO_QUYET_DINH_THA,
    NGAY_QUYET_DINH_THA,
    TOA_QUYET_DINH_THA_ID,
    DIA_PHUONG_QUYET_DINH_THA_ID,
    NGAY_THA,
    NGAY_TRINH_DIEN,
    LY_DO_TRO_LAI_ID,
    LY_DO_CHI_TIET,
    SO_QUYET_DINH_LAI,
    NGAY_QUYET_DINH,
    TOA_QUYET_DINH_LAI_ID,
    DIA_PHUONG_QUYET_DINH_LAI_ID,
    NGAY_QUYET_DINH_TRO_LAI,
    NGAY_BAT_LAI,
    PHAM_NHAN_ID,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,
    QQCT_PHIEU,
    NHAN_XET,
    DANH_GIA_CAI_TAO_ID
)
SELECT
    /* NGAY_XET */
    CAST(TT.NGAY_XET_TT AS TIMESTAMP),

    /* MA_DUOC_TT → TINH_TRANG_ID (CHƯA MAP) */
    DTCDK.ID,

    /* QUYẾT ĐỊNH THA */
    TT.SO_QD_TT,
    CAST(TT.NGAY_QD_TT AS TIMESTAMP),

    /* MA_CQ_TOA_QD_TT → TOA_ID (CHƯA MAP) */
    DCQ.ID,

    /* MA_DP_TOA_QD_TT → DIA_PHUONG_ID (CHƯA MAP) */
    DDVHC.ID,

    CAST(TT.NGAY_THA_TT AS TIMESTAMP),
    CAST(TT.NGAY_TRINH_DIEN_TT AS TIMESTAMP),

    /* LÝ DO TRỞ LẠI */
    LDTL.ID, -- MA_LY_DO_TRO_LAI

    TT.LY_DO_TROLAI_CHITIET,

    /* QUYẾT ĐỊNH TRỞ LẠI */
    TT.SO_QD_TL,
    CAST(TT.NGAY_QD_TL AS TIMESTAMP),

    DCQ2.ID, -- MA_CQ_TOA_QD_TL
    DDVHC2.ID, -- MA_DP_TOA_QD_TL

    CAST(TT.NGAY_QD_TRO_LAI AS TIMESTAMP),
    CAST(TT.NGAY_TRO_LAI_TRAI AS TIMESTAMP),

    PLL2.ID,

    /* AUDIT */
    SYSTIMESTAMP,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,

    /* QQCT_PHIEU */
    TT.KQCT_PHIEU_TT,

    /* NHAN_XET (MERGE 2 FIELD CHO ĐỦ DATA) */
    TT.NHAN_XET_TT || CHR(10) || TT.DANH_GIA_CAI_TAO_TT,

    /* DANH_GIA_CAI_TAO_ID (KHÔNG CÓ MAP) */
    DXLCT.ID

FROM QLPN_OLD.PN_THA_CO_DK TT

LEFT JOIN QLPN_OLD.PN_LAI_LICH PLL
    ON PLL.PN_ID = TT.PN_ID

INNER JOIN QLPN.PN_LAI_LICHS PLL2
    ON PLL2.LL_SO_HO_SO_LAN_DAU = PLL.SO_HSLD
LEFT JOIN QLPN.DM_THA_CO_DIEU_KIENS DTCDK 
	ON DTCDK.TCDK_MA = tt.MA_DUOC_TT
LEFT JOIN QLPN.DM_CO_QUANS DCQ 
	ON DCQ.CQ_MA = tt.MA_CQ_TOA_QD_TT
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DDVHC 
	ON DDVHC.DVHC_MA_DVHC = tt.MA_DP_TOA_QD_TT
LEFT JOIN QLPN.DM_LY_DO_TRO_LAIES LDTL
	ON LDTL.LDTL_MA = TT.MA_LY_DO_TRO_LAI
LEFT JOIN QLPN.DM_CO_QUANS dcq2 
	ON dcq2.CQ_MA = TT.MA_CQ_TOA_QD_TL
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DDVHC2 
	ON DDVHC2.DVHC_MA_DVHC = tt.MA_DP_TOA_QD_TL
LEFT JOIN QLPN.DM_XEP_LOAI_CAI_TAOS DXLCT
	ON DXLCT.XLCT_TEN = TT.DANH_GIA_CAI_TAO_TT;