DELETE FROM QLPN.CHUA_BENH_BAT_BUOCS;



INSERT INTO QLPN.CHUA_BENH_BAT_BUOCS

(PHAM_NHAN_ID, SO_QUYET_DINH, NGAY_QUYET_DINH, CO_QUAN_QUYET_DINH_ID, DIA_PHUONG_QUYET_DINH_ID, THOI_HAN, TU_NGAY

, BENH_TAT_ID, CHI_TIET_BENH, NGAY_BAT_DAU, NGAY_KET_THUC, NOI_CHUA_BENH, CREATION_TIME, IS_DELETED)

SELECT pll.ID_MOI AS PN_ID, QD_SO, QD_NGAY, dcq.ID AS MA_CQ_TOA_AN_QD, ddvhc.ID AS MA_DP_TOA_AN_QD

, dmtg.ID AS MA_MUC_THOI_HAN, TU_NGAY, dbt.ID AS MA_BENH_TAT, BENH_TAT, NGAY_BAT_DAU, NGAY_KET_THUC, NOI_CHUA_BENH

,sysdate as CREATION_TIME,0 as IS_DELETED

FROM QLPN_OLD.PN_CHUA_BENH_BAT_BUOC cbbb

LEFT JOIN (SELECT lln.ID AS ID_MOI

, llo.PN_ID AS ID_CU

FROM QLPN_OLD.PN_LAI_LICH llo

LEFT JOIN QLPN.PN_LAI_LICHS lln

ON lln.LL_SO_HO_SO_LAN_DAU = llo.SO_HSLD) pll

ON cbbb.PN_ID = pll.ID_CU 

LEFT JOIN QLPN.DM_CO_QUANS dcq

ON cbbb.MA_CQ_TOA_AN_QD = dcq.CQ_MA

LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH ddvhc

ON cbbb.MA_DP_TOA_AN_QD = ddvhc.DVHC_MA_DVHC

LEFT JOIN QLPN.DM_BENH_TATS dbt

ON cbbb.MA_BENH_TAT = dbt.BT_MA

LEFT JOIN QLPN.DM_MA_THOI_GIANS dmtg 

ON cbbb.MA_MUC_THOI_HAN = dmtg.MTG_MA