TRUNCATE 
	TABLE QLPN.TAM_DINH_CHIS;

INSERT INTO QLPN.TAM_DINH_CHIS (
    SO_QUYET_DINH,
    NGAY_QUYET_DINH,
    TU_NGAY,
    NGAY_TDC,
    NGAY_LAI,
    NGAY_DE_NGHI,

    LY_DO_CHI_TIET,
    NHAN_XET,

    PHAM_NHAN_ID,

    -- Audit
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,

    -- Các cột FK chưa map → để NULL
    TOA_QUYET_DINH_ID,
    DIA_PHUONG_ID,
    LOAI_QUYET_DINH_ID,
    LY_DO_SUC_KHOE_ID,
    THOI_HAN_ID,
    TC8_DUYET_ID,
    NOI_VE_DIA_PHUONG_ID,
    NOI_VE_XA_ID,
    TINH_TRANG_ID
)
SELECT
    TDC.SO_QD,
    TDC.NGAY_QD,
    TDC.TU_NGAY,
    TDC.NGAY_TDC,
    TDC.NGAY_LAI,
    TDC.NGAY_DE_NGHI,
	
    TDC.NHAN_XET,
    SUBSTR(NHAN_XET, 1, 1000),

    pll2.ID,

    -- Audit (bảng cũ không có → fill default hợp lý)
    SYSTIMESTAMP,         -- CREATION_TIME
    NULL,                 -- CREATOR_USER_ID
    NULL,                 -- LAST_MODIFICATION_TIME
    NULL,                 -- LAST_MODIFIER_USER_ID
    0,                    -- IS_DELETED
    NULL,                 -- DELETER_USER_ID
    NULL,                 -- DELETION_TIME

    -- FK chưa có mapping
    dcq.ID, -- TOA_QUYET_DINH_ID -> MA_CQ_CUA_TOA
    ddvhc.ID, -- DIA_PHUONG_ID -> QLPN.DM_DON_VI_HANH_CHINH
    ntdc.ID, -- LOAI_QUYET_DINH_ID -> QLPN.DM_LOAI_QUYET_DINH_TAM_DINH_CHIES, MA_LENH_TDC
    dldtdc.ID, -- LY_DO_SUC_KHOE_ID -> DM_LY_DO_TAM_DINH_CHIES
    dmtgg.ID, -- THOI_HAN_ID -> MA_MUC_THOI_HAN_TDC
    dmtgtc8.ID, -- TC8_DUYET_ID
    ddvhv.ID, -- NOI_VE_DIA_PHUONG_ID
    ddvhv.ID, -- NOI_VE_XA_ID
    dtttdc.ID  -- TINH_TRANG_ID -> MA_TINH_TRANG_TDC

FROM QLPN_OLD.PN_TDC_TAM_DINH_CHI TDC
INNER JOIN QLPN_OLD.PN_LAI_LICH PLL
ON PLL.PN_ID = TDC.PN_ID
LEFT JOIN QLPN.DM_LY_DO_TAM_DINH_CHIES dldtdc
ON dldtdc.LDTDC_MA = TDC.LY_DO_TDC
LEFT JOIN QLPN.DM_CO_QUANS dcq 
ON dcq.CQ_MA = TDC.MA_CQ_CUA_TOA
INNER JOIN QLPN.PN_LAI_LICHS pll2 
ON pll2.LL_SO_HO_SO_LAN_DAU = PLL.SO_HSLD
LEFT JOIN QLPN.DM_LOAI_QUYET_DINH_TAM_DINH_CHIES ntdc
ON ntdc.LQDTDC_MA = TDC.MA_LENH_TDC
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH ddvhc
ON ddvhc.DVHC_MA_DVHC = TDC.MA_DP_CUA_TOA
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH ddvhv
ON ddvhc.DVHC_MA_DVHC = TDC.MA_DP_NOI_VE
LEFT JOIN QLPN.DM_TINH_TRANG_TAM_DINH_CHIES dtttdc
ON dtttdc.TTTDC_MA = TDC.MA_TINH_TRANG_TDC
LEFT JOIN QLPN.DM_MA_THOI_GIANS dmtgg
ON dmtgg.MTG_MA = TDC.MA_MUC_THOI_HAN_TDC
LEFT JOIN QLPN.DM_MA_THOI_GIANS dmtgtc8
ON dmtgtc8.MTG_MA = TDC.MA_THOI_HAN_TC8;