-- ===== NHÓM CHI TIẾT / PHỤ THUỘC =====

DELETE FROM QLPN.BIEN_BAN_GHI_NHANS;
DELETE FROM QLPN.CHUA_BENH_BAT_BUOCS;
DELETE FROM QLPN.DX_DU_DIEU_KIEN_DAC_XAS;
DELETE FROM QLPN.DX_HINH_PHAT_BO_SUNGS;
DELETE FROM QLPN.DX_THOI_GIAN_CHAP_HANHS;
DELETE FROM QLPN.DX_THOI_GIAN_CON_LAIES;
DELETE FROM QLPN.DX_TOI_DANH_RIENGS;
DELETE FROM QLPN.DX_TRUONG_HOP_DAC_BIETS;
DELETE FROM QLPN.DX_XEP_LOAI_CAI_TAOS;
DELETE FROM QLPN.GTH_HINH_PHAT_BO_SUNGS;
DELETE FROM QLPN.GTH_KY_GIAM_THOI_HANS;
DELETE FROM QLPN.GTH_THOI_GIAN_CHAP_HANHS;
DELETE FROM QLPN.GTH_TRUONG_HOP_DAC_BIETS;
DELETE FROM QLPN.GTH_XEP_LOAI_CAI_TAOS;





-- KỲ XẾP LOẠI CẢI TẠO

DELETE FROM QLPN.MO_KY_XEP_LOAI_CAI_TAO_PN_LAI_LICH;
DELETE FROM QLPN.MO_KY_XEP_LOAI_CAI_TAOS;



-- ===== NHÓM NGHIỆP VỤ =====

DELETE FROM QLPN.PN_DU_DIEU_KIEN_XET_THAS;
DELETE FROM QLPN.PN_DOT_THA_CO_DIEU_KIENS;





DELETE FROM QLPN.GIAM_THOI_HANS;
DELETE FROM QLPN.HOAN_THI_HANH_ANS;
DELETE FROM QLPN.KHEN_THUONGS;
DELETE FROM QLPN.MIEN_HINH_PHATS;
DELETE FROM QLPN.TRON_TRAIS;
DELETE FROM QLPN.TRICH_XUATS;
DELETE FROM QLPN.PN_KET_THUC_CHETS;
DELETE FROM QLPN.PN_KET_THUC_RA_TRAIS;
DELETE FROM QLPN.PN_GIAM_RIENGS;
DELETE FROM QLPN.PN_DAC_XAS;

DELETE FROM QLPN.PN_CHUYEN_GIAO;

DELETE FROM QLPN.PN_BAN_AN_KHACS;

DELETE FROM QLPN.PN_SUC_KHOES;





-- ===== NHÓM PHẠM NHÂN (ĐÚNG ERD) =====

DELETE FROM QLPN.PHAM_NHAN_CHUYEN_TRAI;

DELETE FROM QLPN.PHAM_NHAN_PHAN_DOI;

DELETE FROM QLPN.PHAM_NHAN_PHAN_BUONG;

DELETE FROM QLPN.PN_NGHIEN_MT;

DELETE FROM QLPN.PN_NHAN_DANGS;

DELETE FROM QLPN.PN_QUYET_DINH_BAN_AN_KHACS;

DELETE FROM QLPN.PN_TAI_LIEU_DINH_KEMS;

DELETE FROM QLPN.PN_THI_HANH_AN;

DELETE FROM QLPN.PN_TIEN_AN;

DELETE FROM QLPN.PN_TIEN_SUS;

DELETE FROM QLPN.TAM_DINH_CHIS;

DELETE FROM QLPN.NOP_LUUS;

DELETE FROM QLPN.XEP_LOAIS;

DELETE FROM QLPN.THA_CO_DIEU_KIENS;

DELETE FROM QLPN.THAN_NHAN_CON_CAIS;

DELETE FROM QLPN.THAN_NHAN_NGUOI_THANS;

DELETE FROM QLPN.CHUA_BENH_BAT_BUOCS;

DELETE FROM QLPN.PN_HINH_PHAT_BO_SUNGS;





DELETE FROM QLPN.PN_LAI_LICHS;



-- Đặc Xá 

DELETE FROM QLPN.DX_DIEU_KIEN_DAC_XAS;

DELETE FROM QLPN.PN_DOT_DAC_XAS;



-- GIẢM THỜI HẠN

DELETE FROM QLPN.GTH_DIEU_KIEN_GIAM_THOI_HANS;





DELETE FROM QLPN.PN_GIAO_NHAN_PHAN_NHANS;



COMMIT;