-- New script in ORCL.
-- Date: Mar 17, 2026
-- Time: 6:02:23 PM
TRUNCATE TABLE QLPN.MO_KY_XEP_LOAI_CAI_TAOS;

INSERT INTO QLPN.MO_KY_XEP_LOAI_CAI_TAOS (
    NAM_XEP_LOAI,
    TU_NGAY,
    DEN_NGAY,
    NGAY_DEN_TRAI_TU,
    TRANG_THAI,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,
    KY_XEP_LOAI,
    NGAY_HOP_XEP_LOAI,
    NGAY_QDXEP_LOAI,
    NGAY_TBCHO_GIA_DINH,
    SO_QUYET_DINH_TU,
    SO_THONG_BAO_TU
)
SELECT
    okxl.NAM_XL,

    CAST(okxl.TU_NGAY_XL AS TIMESTAMP),
    CAST(okxl.DEN_NGAY_XL AS TIMESTAMP),

    /* TU_NGAY_DEN_TRAI → NGAY_DEN_TRAI_TU */
    CAST(okxl.TU_NGAY_DEN_TRAI AS TIMESTAMP),

    /* TRANG_THAI (không có trong OLD → default) */
    1,

    /* Audit */
    SYSTIMESTAMP,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,

    /* KY_XEP_LOAI */
    SUBSTR(okxl.KY_XEP_LOAI, 1, 10),

    CAST(okxl.NGAY_HOP_XEP_LOAI AS TIMESTAMP),
    CAST(okxl.NGAY_QD_XL AS TIMESTAMP),
    CAST(okxl.NGAY_TB_XL AS TIMESTAMP),

    /* TU_SO_QD → SO_QUYET_DINH_TU */
    TO_CHAR(okxl.TU_SO_QD),

    /* TU_SO_TB → SO_THONG_BAO_TU */
    TO_CHAR(okxl.TU_SO_TB)

FROM QLPN_OLD.PN_OPEN_KY_XEP_LOAI okxl;