-- New script in ORCL.
-- Date: Mar 17, 2026
-- Time: 2:34:58 PM
TRUNCATE
	TABLE QLPN.PN_TIEN_SUS;

INSERT
	INTO
	QLPN.PN_TIEN_SUS
(
	TS_SO_QUYET_DINH,
	TS_NGAY_QUYET_DINH,
	TS_HANH_VI_VI_PHAM,
	TS_DON_VI_XU_LY,
	TS_HINH_THUC_XU_LY,
	TS_NOI_CHAP_HANH,
	TS_NGAY_BAT_DAU,
	TS_NGAY_KET_THUC,
	TS_GHI_CHU,
	TS_THOI_GIAN,
	TS_PN_LAI_LICH_ID,
	CREATION_TIME,
	CREATOR_USER_ID,
	LAST_MODIFICATION_TIME,
	LAST_MODIFIER_USER_ID,
	IS_DELETED,
	DELETER_USER_ID,
	DELETION_TIME)
SELECT
	QD_SO,
	QD_NGAY,
	HANH_VI_VP,
	DON_VI_XL,
	HINH_THUC_XL,
	NOI_CHAP_HANH,
	-- Convert string → timestamp
    CASE
		WHEN REGEXP_LIKE(NGAY_BAT_DAU, '^\d{2}/\d{2}/\d{4}$')
        THEN TO_TIMESTAMP(NGAY_BAT_DAU, 'DD/MM/YYYY')
		ELSE NULL
	END,
	CASE
		WHEN REGEXP_LIKE(NGAY_KET_THUC, '^\d{2}/\d{2}/\d{4}$')
        THEN TO_TIMESTAMP(NGAY_KET_THUC, 'DD/MM/YYYY')
		ELSE NULL
	END,
	GHI_CHU_TS,
	-- default value theo schema mới
	TIMESTAMP '0001-01-01 00:00:00',
	pll2.ID,
	SYSTIMESTAMP,
    NULL,         -- CREATOR_USER_ID
    NULL,         -- LAST_MODIFICATION_TIME
    NULL,         -- LAST_MODIFIER_USER_ID
    0,            -- IS_DELETED
    NULL,         -- DELETER_USER_ID
    NULL          -- DELETION_TIME
FROM
	QLPN_OLD.PN_TIEN_SU TSO
INNER JOIN QLPN_OLD.PN_LAI_LICH PLL
ON PLL.PN_ID = TSO.PN_ID
INNER JOIN QLPN.PN_LAI_LICHS pll2 
ON pll2.LL_SO_HO_SO_LAN_DAU = PLL.SO_HSLD;