DELETE FROM QLPN.DM_BAN_GIAO_TRICH_XUATS;
INSERT INTO QLPN.DM_BAN_GIAO_TRICH_XUATS (BGTX_MA, BGTX_TEN, BGTX_TRANG_THAI, CREATION_TIME, IS_DELETED)



SELECT MA, ND, 1 AS BGT_TRANG_THAI, SYSDATE AS CREATION_TIME, 0 AS IS_DELETED 
FROM QLPN_OLD.MA_BAN_GIAO_TX;