
DELETE FROM QLPN.PHAM_NHAN_CHUYEN_TRAI;
INSERT INTO QLPN.PHAM_NHAN_CHUYEN_TRAI (PNCT_CONG_VAN_DE_NGHI_SO,PNCT_CONG_VAN_DE_NGHI_NGAY,PNCT_CO_QUAN_DE_NGHI_CHUYEN_ID,

PNCT_SO_QDDIEU_CHUYEN,PNCT_NGAY_QDCHUYEN,PNCT_TRUONG_HOP_CHUYEN_ID,PNCT_NGAY_CHUYEN,

PNCT_TRAI_DEN_ID,PNCT_NGAY_TRO_LAI,PNCT_SO_QDDIEU_CHUYEN_LAI,PNCT_NGAY_QDDIEU_CHUYEN_LAI,PNCT_GHI_CHU,

PNCT_LAI_LICH_ID,PNCT_CO_QUAN_DE_NGHI_DIA_PHUONG_ID,PNCT_TRAI_DEN_DIA_PHUONG_ID,CREATION_TIME,

CREATOR_USER_ID,LAST_MODIFICATION_TIME,LAST_MODIFIER_USER_ID,IS_DELETED,DELETER_USER_ID,DELETION_TIME)



SELECT 

     CV_DN_CHUYEN_SO AS PNCT_CONG_VAN_DE_NGHI_SO,

     CV_DN_CHUYEN_NGAY AS PNCT_CONG_VAN_DE_NGHI_NGAY,

     MA_CQ_DN_CHUYEN AS PNCT_CO_QUAN_DE_NGHI_CHUYEN_ID,

     SO_QD_CHUYEN AS PNCT_SO_QDDIEU_CHUYEN,

     NGAY_QD_CHUYEN AS PNCT_NGAY_QDCHUYEN,

     MA_TRUONG_HOP_CHUYEN AS PNCT_TRUONG_HOP_CHUYEN_ID,

     NGAY_CHUYEN AS PNCT_NGAY_CHUYEN,

     MA_CQ_TRAI_DEN AS PNCT_TRAI_DEN_ID,

     NGAY_TRO_LAI AS PNCT_NGAY_TRO_LAI,

     QD_TRO_LAI_SO AS PNCT_SO_QDDIEU_CHUYEN_LAI,

     QD_TRO_LAI_NGAY AS PNCT_NGAY_QDDIEU_CHUYEN_LAI,

     GHI_CHU AS PNCT_GHI_CHU,

     ID AS PNCT_LAI_LICH_ID,

     NULL AS PNCT_CO_QUAN_DE_NGHI_DIA_PHUONG_ID,

     NULL AS PNCT_TRAI_DEN_DIA_PHUONG_ID,

     SYSDATE AS CREATION_TIME,

     NULL AS CREATOR_USER_ID,

     NULL AS LAST_MODIFICATION_TIME,

     NULL AS LAST_MODIFIER_USER_ID,

     0 AS IS_DELETED,

     NULL AS DELETER_USER_ID,

    NULL AS DELETION_TIME

FROM "QLPN_OLD"."PN_CHUYEN_TRAI" A

INNER JOIN "QLPN_OLD".PN_LAI_LICH B

ON A.PN_ID =B.PN_ID 

INNER JOIN "QLPN".PN_LAI_LICHS C

ON B.SO_HSLD = C.LL_SO_HO_SO_LAN_DAU;

