-- New script in ORCL.
-- Date: Mar 17, 2026
-- Time: 3:51:37 PM
TRUNCATE TABLE QLPN.THAN_NHAN_CON_CAIS;

INSERT INTO QLPN.THAN_NHAN_CON_CAIS (
    HO_TEN_CON,
    GIOI_TINH_ID,
    NGAY_SINH,
    TRUONG_HOP_SINH_ID,
    NOI_SINH,
    NGAY_DEN,
    NGAY_RA,
    PHAM_NHAN_ID,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,
    TINH_TRANG_ID,
    GHI_CHU
)
SELECT
    cpn.HO_TEN_CPN,

    GT.ID,
    CASE 
        WHEN cpn.NGAY_SINH_CPN IS NOT NULL 
        THEN TO_CHAR(cpn.NGAY_SINH_CPN, 'YYYY-MM-DD')
        ELSE NULL
    END,

    THS.ID,

    cpn.NOI_SINH_CPN,

    /* DATE → TIMESTAMP */
    CAST(cpn.NGAY_DEN_CPN AS TIMESTAMP),

    CAST(cpn.NGAY_RA_CPN AS TIMESTAMP),

    /* map qua PN_LAI_LICHS */
    pll2.ID,

    /* Audit fields */
    SYSTIMESTAMP,   -- CREATION_TIME
    NULL,           -- CREATOR_USER_ID
    NULL,           -- LAST_MODIFICATION_TIME
    NULL,           -- LAST_MODIFIER_USER_ID
    0,              -- IS_DELETED
    NULL,           -- DELETER_USER_ID
    NULL,           -- DELETION_TIME
    
    tmvt.ID,

    /* VARCHAR2 → NCLOB ok */
    cpn.GHI_CHU_CPN

FROM QLPN_OLD.PN_CON_PHAM_NHAN cpn

LEFT JOIN QLPN_OLD.PN_LAI_LICH pll
    ON pll.PN_ID = cpn.PN_ID

LEFT JOIN QLPN.PN_LAI_LICHS pll2
    ON pll2.LL_SO_HO_SO_LAN_DAU = pll.SO_HSLD
LEFT JOIN QLPN.DM_GIOI_TINHS gt
	ON gt.GT_MA = cpn.MA_GIOI_TINH_CPN
LEFT JOIN QLPN.DM_TRUONG_HOP_SINH_CON_THEO_MES THS
	ON THS.SCTM_MA = cpn.MA_TH_SINH_CPN
LEFT JOIN QLPN.DM_TINH_TRANG_CON_THEO_ME_VAO_TRAIES tmvt
	ON tmvt.TTCTMVT_MA = cpn.MA_TINH_TRANG_CPN;