DELETE FROM QLPN.PN_DOT_THA_CO_DIEU_KIENS;
INSERT INTO QLPN.PN_DOT_THA_CO_DIEU_KIENS
(
DTCDK_NGAY_XET,
DTCDK_NGAY_HOP,
DTCDK_SO_PHIEU,
DTCDK_SO_GCN_TU,
DTCDK_DM_CO_QUAN_ID,
CREATION_TIME,
IS_DELETED
)
SELECT
NGAY_XET_THA,
NGAY_HOP_XET,
TU_SO_PHIEU,
TU_SO_GCN,
CQ.ID MA_CQ_TOA_QD_THA,
CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
0 AS IS_DELETED
FROM QLPN_OLD.PN_OPEN_KY_THA_CO_DK TCDK
LEFT JOIN QLPN.DM_CO_QUANS CQ  ON CQ.CQ_MA = TCDK.MA_CQ_TOA_QD_THA