DELETE FROM QLPN.PN_NGHIEN_MT;

INSERT INTO QLPN.PN_NGHIEN_MT

(NMT_CHAT_MA_TUY,

NMT_HINH_THUC_SD,

NMT_CAN_CU_XAC_DINH,

NMT_THOI_GIAN_SD,

NMT_TINH_TRANG_CAI_NGHIEN,

NMT_GHI_CHU,

NMT_TRUONG_HOP_NGHIEN,

NMT_TRUONG_HOP_CAI,

NMT_THANH_PHAN_BAN_THAN,

NMT_TRINH_DO_HOC_VAN,

NMT_TINH_TRANG_HON_NHAN,

NMT_HOAN_CANH_GIA_DINH,

NMT_NGHE_NGHIEP_BO_ME,

NMT_KINH_TE_GIA_DINH,

NMT_SO_LAN_SD,

NMT_DO_TUOI_SD,

NMT_GIA_TIEN_SD_MOI_LAN,

NMT_THOI_HAN_SD,

NMT_NGUON_TIEN_MUA_MT,

NMT_DONG_CO_NGHIEN,

NMT_TINH_TRANG_NGHIEN,

NMT_NGUYEN_NHAN_TAI_NGHIEN,

NMT_BIEN_PHAP_CAI_HIEU_QUA,

NMT_YEU_TO_CAI_NGHIEN,

NMT_DE_XUAT_VOI_XA_HOI,

NMT_DE_XUAT_VOI_TRAI_GIAM,

NMT_DE_XUAT_VOI_BAN_THAN,

NMT_CAM_DOAN_CUA_BAN_THAN,

NMT_PN_LAI_LICH_ID,

CREATION_TIME,

IS_DELETED

)



SELECT 

CMT.ID MA_CHAT_MA_TUY,

HTSDMT.ID MA_HINH_THUC_SD,

CCXDMT.ID MA_CAN_CU_XAC_DINH,

MTGSUMT.ID MA_THOI_GIAN_SD,

TTCNMT.ID MA_TINH_TRANG_CAI_NGHIEN,

GHI_CHU,

THNMT.ID MA_TRUONG_HOP_NGHIEN,

MTHC.ID MA_TRUONG_HOP_CAI,

MTPBT.ID MA_TP_BAN_THAN,

MTDHV.ID MA_TRINH_DO_HV,

MTTHN.ID MA_TINH_TRANG_HON_NHAN,

MHCGD.ID MA_HOAN_CANH_GD,

MNNBM.ID MA_NGHE_BO_ME,

MTTKTGD.ID MA_TINH_TRANG_KT_GD,

SLSDMT.ID MA_SO_LAN_SD,

DTSDMT.ID MA_DO_TUOI_SD,

GIA_TIEN_SD_MOI_LAN,

TGSDMT.ID MA_THOI_GIAN_SD,

NTMMT.ID MA_NGUON_TIEN_MUA_MT,

DCSDMT.ID MA_DONG_CO_NGHIEN,

TTNMT.ID MA_TINH_TRANG_NGHIEN,

NNTNMT.ID MA_NGUYEN_NHAN_TAI_NGHIEN,

BPCNMT.ID MA_BP_CAI_NGHIEN_HQ,

MYTCNHQ.ID MA_YEU_TO_CAI_NGHIEN,

DE_XUAT_VOI_XA_HOI,

DE_XUAT_VOI_TG,

DE_XUAT_VOI_BAN_THAN,

CAM_DOAN_BAN_THAN,

LLN.ID PN_ID,

CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,

0 AS IS_DELETED

FROM QLPN_OLD.PN_DOI_TUONG_NGHIEN_MT DTNMT

 INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON DTNMT.PN_ID = LL.PN_ID

 INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU

 LEFT JOIN QLPN.DM_CHAT_MA_TUIES CMT ON CMT.CMT_MA = DTNMT.MA_CHAT_MA_TUY

LEFT JOIN QLPN.DM_HINH_THUC_SU_DUNG_MA_TUIES HTSDMT ON HTSDMT.HTSDMT_MA = DTNMT.MA_HINH_THUC_SD

LEFT JOIN QLPN.DM_CAN_CU_XAC_DINH_MA_TUIES CCXDMT ON CCXDMT.CCXDMT_MA = DTNMT.MA_CAN_CU_XAC_DINH

LEFT JOIN QLPN.DM_MT_THOI_GIAN_SU_DUNG_MA_TUIES MTGSUMT ON MTGSUMT.TGSDMT_MA = DTNMT.MA_THOI_GIAN_SD

LEFT JOIN QLPN.DM_MT_TINH_TRANG_CAI_NGHIEN_MA_TUIES TTCNMT ON TTCNMT.TTCNMT_MA = DTNMT.MA_TINH_TRANG_CAI_NGHIEN

LEFT JOIN QLPN.DM_MT_TRUONG_HOP_NGHIEN_MA_TUIES THNMT ON THNMT.THNMT_MA = DTNMT.MA_TRUONG_HOP_NGHIEN

LEFT JOIN QLPN.DM_MT_TRUONG_HOP_CAIES MTHC ON MTHC.MTHC_MA = DTNMT.MA_TRUONG_HOP_CAI

LEFT JOIN QLPN.DM_MT_THANH_PHAN_BAN_THANS MTPBT ON MTPBT.MTPBT_MA = DTNMT.MA_TP_BAN_THAN

LEFT JOIN QLPN.DM_MT_TRINH_DO_HOC_VANS MTDHV ON MTDHV.MTDHV_MA = DTNMT.MA_TRINH_DO_HV

LEFT JOIN QLPN.DM_MT_TINH_TRANG_HON_NHANS MTTHN ON  MTTHN.MTTHN_MA = DTNMT.MA_TINH_TRANG_HON_NHAN

LEFT JOIN QLPN.DM_MT_HOAN_CANH_GIA_DINHS MHCGD ON MHCGD.MHCGD_MA = DTNMT.MA_HOAN_CANH_GD

LEFT JOIN QLPN.DM_MT_NGHE_NGHIEP_BO_MES MNNBM ON MNNBM.MNNBM_MA = DTNMT.MA_NGHE_BO_ME

LEFT JOIN QLPN.DM_MT_TINH_TRANG_KINH_TE_GIA_DINHS MTTKTGD ON MTTKTGD.MTTKTGD_MA = DTNMT.MA_TINH_TRANG_KT_GD

LEFT JOIN QLPN.DM_SO_LAN_SU_DUNG_MA_TUYS SLSDMT ON SLSDMT.SLSDMT_MA = DTNMT.MA_SO_LAN_SD

LEFT JOIN QLPN.DM_DO_TUOI_SU_DUNG_MA_TUIES DTSDMT ON DTSDMT.DTSDMT_MA = DTNMT.MA_DO_TUOI_SD

LEFT JOIN QLPN.DM_MT_THOI_GIAN_SU_DUNG_MA_TUIES TGSDMT ON  TGSDMT.TGSDMT_MA= DTNMT.MA_THOI_GIAN_SD

LEFT JOIN QLPN.DM_NGUON_TIEN_MUA_MA_TUIES NTMMT ON NTMMT.NTMMT_MA = DTNMT.MA_NGUON_TIEN_MUA_MT

LEFT JOIN QLPN.DM_DONG_CO_SU_DUNG_MA_TUIES DCSDMT ON DCSDMT.DCSDMT_MA = DTNMT.MA_DONG_CO_NGHIEN

LEFT JOIN QLPN.DM_MT_TINH_TRANG_NGHIEN_MA_TUIES TTNMT ON TTNMT.TTNMT_MA = DTNMT.MA_TINH_TRANG_NGHIEN

LEFT JOIN QLPN.DM_NGUYEN_NHAN_TAI_NGHIEN_MA_TUIES NNTNMT ON NNTNMT.NNTNMT_MA = DTNMT.MA_NGUYEN_NHAN_TAI_NGHIEN

LEFT JOIN QLPN.DM_BIEN_PHAP_CAI_NGHIEN_MA_TUIES BPCNMT ON BPCNMT.BPCNMT_MA  = DTNMT.MA_BP_CAI_NGHIEN_HQ

LEFT JOIN QLPN.DM_MT_YEU_TO_CAI_NGHIEN_HIEU_QUAS MYTCNHQ ON MYTCNHQ.MYTCNHQ_MA = DTNMT.MA_YEU_TO_CAI_NGHIEN