DELETE FROM QLPN.PN_HINH_PHAT_BO_SUNGS;

INSERT INTO QLPN.PN_HINH_PHAT_BO_SUNGS
(
    HPBS_HINH_PHAT,
    HPBS_MA_PHAM_NHAN,
    HPBS_THOI_HAN,
    HPBS_TONG_TIEN_PHAT,
    HPBS_HE_SO,
    HPBS_GHI_CHU,
    HPBS_GHI_CHU_CHI_TIET,
    CREATION_TIME,
    IS_DELETED,
    HPBS_TONG_TIEN_CON_LAI
)
SELECT  /*+ USE_HASH( LL  LLN) */
    TO_NUMBER(MA_HINH_PHAT DEFAULT NULL ON CONVERSION ERROR) MA_HINH_PHAT,
    LLN.ID,
    TO_NUMBER(MA_MUC_THOI_HAN DEFAULT NULL ON CONVERSION ERROR) MA_MUC_THOI_HAN,
    TONG_TIEN_PHAT,
    TO_NUMBER(MA_HE_SO_TIEN DEFAULT NULL ON CONVERSION ERROR) MA_HE_SO_TIEN,
    TO_NUMBER(MA_GHI_CHU_HPBS DEFAULT NULL ON CONVERSION ERROR) MA_GHI_CHU_HPBS,
    GHI_CHU_HPBS_HP,
    CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
    0 AS IS_DELETED,
    TONG_TIEN_PHAT-NVL(TONG_DA_NOP,0) as HPBS_TONG_TIEN_CON_LAI
FROM QLPN_OLD.PN_HPBS_HINH_PHAT HPBS
 INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON HPBS.PN_ID = LL.PN_ID
 INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU