DELETE FROM QLPN.PN_THI_HANH_AN;



INSERT INTO QLPN.PN_THI_HANH_AN

(THA_SO_BAN_AN,

THA_NGAY_QD_THA,

THA_NGAY_BAN_AN,

THA_TOA_QD_ID,

THA_GHI_CHU_DAC_BIET,

THA_SO_QD_THA,

THA_CAP_TOA_ID,

THA_DIA_PHUONG_TOA_QD_THA_ID,

THA_DIA_PHUONG_CAP_TOA_ID,

THA_PNLAI_LICH_ID,

CREATION_TIME,

IS_DELETED

)



select  /*+ USE_HASH( LL  LLN) */

QDTHA.SO_BAN_AN,

QDTHA.NGAY_QDTH_AN,

QDTHA.NGAY_BAN_AN,

CQ.ID MA_CQ_TOA_QDTH_AN,

QDTHA.GHI_CHU_QDTHA,

QDTHA.SO_QDTH_AN,

CQQ.ID MA_CQ_TOA_XU,

DVHC.ID MA_DP_TOA_QDTH_AN,

DVHCC.ID MA_DP_TOA_XU,

LLN.ID PN_ID,

CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,

0 AS IS_DELETED

FROM QLPN_OLD.PN_QD_THI_HANH_AN QDTHA

INNER JOIN QLPN_OLD.PN_LAI_LICH LL  ON QDTHA.PN_ID = LL.PN_ID

INNER JOIN QLPN.PN_LAI_LICHS LLN  ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU

LEFT JOIN QLPN.DM_CO_QUANS CQ  ON CQ.CQ_MA = QDTHA.MA_CQ_TOA_QDTH_AN

LEFT JOIN QLPN.DM_CO_QUANS CQQ  ON CQQ.CQ_MA = QDTHA.MA_CQ_TOA_XU

LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DVHC ON DVHC.DVHC_MA_DVHC = QDTHA.MA_DP_TOA_XU

LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DVHCC ON DVHCC.DVHC_MA_DVHC = QDTHA.MA_DP_TOA_XU