services:
  etl-job-config:
    image: etl-job-config:v1
    container_name: etl-job-config
    ports:
      - "5333:5333"
    volumes:
      - D:\thangnd\spark-minio_hive_metastore\spark-minio_hive_metastore\sql:/app/sql
    restart: unless-stopped

#hhhh
