-- New script in ORCL.
-- Date: Mar 17, 2026
-- Time: 3:28:43 PM
TRUNCATE 
	TABLE QLPN.TANG_GIAM_HINH_PHATS;

INSERT INTO QLPN.TANG_GIAM_HINH_PHATS (
    LOAI_TANG_GIAM_ID,
    SO_QUYET_DINH,
    NGAY_QUYET_DINH,
    DON_VI_QUYET_DINH_ID,
    DIA_PHUONG_QUYET_DINH_ID,
    GHI_CHU,
    PHAM_NHAN_ID,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,
    THOI_HAN_ID
)
SELECT
     --→ LOAI_TANG_GIAM_ID
	 dtghp.ID,
     tghp.SO_QD,
	 tghp.NGAY_QD,

     dcq.ID, --→ DON_VI_QUYET_DINH_ID


     DDVHC.ID, --→ DIA_PHUONG_QUYET_DINH_ID

    tghp.GHI_CHU_TGHP,

    pll2.ID,
    -- Audit
    SYSTIMESTAMP,  -- CREATION_TIME
    NULL,          -- CREATOR_USER_ID
    NULL,          -- LAST_MODIFICATION_TIME
    NULL,          -- LAST_MODIFIER_USER_ID
    0,             -- IS_DELETED
    NULL,          -- DELETER_USER_ID
    NULL,          -- DELETION_TIME

    -- MTG_MA MA_MUC_THOI_HAN → THOI_HAN_ID
    dmtg.ID

FROM QLPN_OLD.PN_TANG_GIAM_HINH_PHAT tghp
LEFT JOIN QLPN_OLD.PN_LAI_LICH PLL
ON PLL.PN_ID = tghp.PN_ID
INNER JOIN QLPN.PN_LAI_LICHS pll2 
ON pll2.LL_SO_HO_SO_LAN_DAU = PLL.SO_HSLD
LEFT JOIN QLPN.DM_LOAI_TANG_GIAM_HINH_PHATS dtghp
ON tghp.MA_LOAI_TGHP = dtghp.LTGHP_MA
LEFT JOIN QLPN.DM_CO_QUANS DCQ 
	ON DCQ.CQ_MA = tghp.MA_CQ_TOA_QD
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DDVHC 
	ON DDVHC.DVHC_MA_DVHC = tghp.MA_DP_TOA_QD
LEFT JOIN QLPN.DM_MA_THOI_GIANS dmtg
	ON dmtg.MTG_MA = tghp.MA_MUC_THOI_HAN;