
DELETE
FROM QLPN.PN_LAI_LICHS;


INSERT INTO QLPN.PN_LAI_LICHS (LL_SO_HO_SO_LAN_DAU, LL_SO_HO_PHU, LL_CCCD, LL_HO_CHIEU, LL_HO_TEN, LL_TEN_KHAC, LL_DIA_CHI_THUONG_TRU, LL_NOI_OTRUOC_KHI_BAT, LL_NOI_THA_VE_CU_TRU, LL_NOI_OKHAC, LL_NGUYEN_QUAN, LL_CHI_TIET_HV, LL_TOM_TAT_HV, LL_CHI_MUC_TIM_KIEM, LL_TRINH_DO_CHUYEN_MON, LL_NGHE_CU_THE, LL_CHI_TIET_BENH_VAO, LL_CHI_TIET_BENH_HIEN_TAI, LL_GHI_CHU_RIENG, LL_PHAN_DOI_ID, LL_TINH_TRANG_ID, LL_TRAI_GIAM_ID, LL_TINH_TRANG_HOC_TAP_ID, LL_NGAY_SINH, LL_GHI_CHU_CHUNG_HPBS, LL_BIET_DOC_VIET_ID, LL_BENH_TAT_VAO_ID, LL_DM_GIOI_TINH_ID, LL_DM_NGHE_NGHIEP_ID, LL_DM_HOC_VAN_ID, LL_DM_QUOC_TICH_ID, LL_DM_TON_GIAO_ID, LL_DM_DAN_TOC_ID, LL_SUC_KHOE_KHI_VAO_ID, LL_SO_TIEN_SU, LL_GHI_CHU_TIEN_SU, LL_SO_TIEN_AN, LL_TAI_PHAM, LL_NHAN_THAN, CREATION_TIME, IS_DELETED)
SELECT SO_HSLD,
       SO_HSPHU,
       CASE
           WHEN NOT REGEXP_LIKE(COALESCE(SO_CCCD, SO_CMND), '[[:alpha:]]') THEN COALESCE(SO_CCCD, SO_CMND)
           ELSE NULL
       END AS CCCD,
       CASE
           WHEN REGEXP_LIKE(COALESCE(SO_CCCD, SO_CMND), '[[:alpha:]]') THEN COALESCE(SO_CCCD, SO_CMND)
           ELSE NULL
       END AS HO_CHIEU,
       HO_TEN,
       TEN_KHAC,
       pll.DC_TT_THON_PHO || ', ' || pll.DC_TT_PHUONG_XA || ', ' || mtt.ND AS DIA_CHI_THUONG_TRU_CU,
       pll.DC_VAO_THON_PHO || ', ' || pll.DC_VAO_PHUONG_XA || ', ' || mvao.ND AS NOI_OTRUOC_KHI_BAT_CU,
       pll.DC_VE_THON_PHO || ', ' || pll.DC_VE_PHUONG_XA || ', ' || mve.ND AS NOI_THA_VE_CU_TRU_CU,
       CHO_O_KHAC,
       NGUYEN_QUAN,
       CHI_TIET_HV,
       TOM_TAT_HV,
       CHI_MUC_TIM_KIEM,
       TRINH_DO_CHUYEN_MON,
       NGHE_CU_THE,
       BENH_TAT_VAO,
       BENH_TAT_HT,
       GHI_CHU_RIENG,
       dbt.ID AS MA_PHAN_DOI,
       ttpn.ID AS MA_TINH_TRANG,
       trg.ID AS MA_TRAI_GIAM,
       ttht.ID AS MA_TINH_TRANG_HOC_TAP,
       NGAY_SINH_PN,
       GHI_CHU_HPBS,
       bdv.ID AS MA_TINH_TRANG_DOC_VIET,
       bt.ID AS MA_BENH_TAT_VAO,
       gt.ID AS MA_GIOI_TINH,
       nn.ID AS MA_NGHE_NGHIEP,
       hv.ID AS MA_HOC_VAN,
       qt.ID AS MA_QUOC_TICH,
       tg.ID AS MA_TON_GIAO,
       dt.ID AS MA_DAN_TOC,
       sk.ID AS MA_SUC_KHOE_VAO,
       SO_TIEN_SU,
       GHI_CHU_TIEN_SU,
       SO_TIEN_AN,
       tp.ID AS MA_TAI_PHAM,
       NHAN_THAN,
       SYSDATE AS CREATION_TIME,
       0 AS IS_DELETED
FROM QLPN_OLD.PN_LAI_LICH pll
LEFT JOIN QLPN.DM_PHAN_DOIS dbt ON pll.MA_PHAN_DOI = dbt.PD_MA
AND dbt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_PHAM_NHANS ttpn ON pll.MA_TINH_TRANG = ttpn.TTPN_MA
AND ttpn.IS_DELETED = 0
LEFT JOIN QLPN.DM_TRAI_GIAMS trg ON pll.MA_TRAI_GIAM = trg.TG_MA
AND trg.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_HOC_TAP_PHAM_NHAN_VI_THANH_NIENS ttht ON pll.MA_TINH_TRANG_HOC_TAP = ttht.TTHTPNVTN_MA
AND ttht.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_BIET_DOC_VIETS bdv ON pll.MA_TINH_TRANG_DOC_VIET = bdv.TTBDV_MA
AND bdv.IS_DELETED = 0
LEFT JOIN QLPN.DM_BENH_TATS bt ON pll.MA_BENH_TAT_VAO = bt.BT_MA
AND bt.IS_DELETED = 0
LEFT JOIN QLPN.DM_GIOI_TINHS gt ON pll.MA_GIOI_TINH = gt.GT_MA
AND gt.IS_DELETED = 0
LEFT JOIN QLPN.DM_NGHE_NGHIEPS nn ON pll.MA_NGHE_NGHIEP = nn.NN_MA
AND nn.IS_DELETED = 0
LEFT JOIN QLPN.DM_HOC_VANS hv ON pll.MA_HOC_VAN = hv.HV_MA
AND hv.IS_DELETED = 0
LEFT JOIN QLPN.DM_QUOC_TICHS qt ON pll.MA_QUOC_TICH = qt.QT_MA
AND qt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TON_GIAOS tg ON pll.MA_TON_GIAO = tg.TG_MA
AND tg.IS_DELETED = 0
LEFT JOIN QLPN.DM_DAN_TOCS dt ON pll.MA_DAN_TOC = dt.DT_MA
AND dt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_SUC_KHOE_PHAM_NHANS sk ON pll.MA_SUC_KHOE_VAO = sk.TTSKPN_MA
AND sk.IS_DELETED = 0
LEFT JOIN QLPN.DM_TAI_PHAMS tp ON pll.MA_TAI_PHAM = tp.TP_MA
AND tp.IS_DELETED = 0
LEFT JOIN QLPN_OLD.MA_DP mtt ON pll.MA_DP_DC_TT = mtt.MA
LEFT JOIN QLPN_OLD.MA_DP mvao ON pll.MA_DP_DC_VAO = mvao.MA
LEFT JOIN QLPN_OLD.MA_DP mve ON pll.MA_DP_DC_VE = mve.MA;