delete from QLPN.GIAM_THOI_HANS;

INSERT INTO QLPN.GIAM_THOI_HANS

  (NGAY_XET,
   
   DA_CHAP_HANH,
   
   DA_GIAM, 
   
   CON_LAI,
   
   MUC_DE_NGHI_ID,
   
   CAP_TREN_DUYET_ID,
   
   SO_QUYET_DINH,
   
   NGAY_QUYET_DINH,
   
   MUC_GIAM_ID,
   
   TOA_QUYET_DINH_ID,
   
   DIA_PHUONG_ID,
   
   NGAY_THA_GIAM_HET_AN,
   
   PHAM_NHAN_ID,
   
   CREATION_TIME,
   
   IS_DELETED,
   
   NHAN_XET,
   
   KQCT_PHIEU,
   
   KQCT_DANHSACH)

  select
  
   PGTG.NGAY_XET NGAY_XET,
   
   MTGCH.MTG_TITLE DA_CHAP_HANH,
   
   MTGG.MTG_TITLE DA_GIAM, --TAM DE NULL
   
   MTGCL.MTG_TITLE CON_LAI,
   
   MTGMDN.ID MUC_DE_NGHI_ID,
   
   MTGBCA.ID CAP_TREN_DUYET_ID,
   
   PGTG.SO_QD_GIAM SO_QUYET_DINH,
   
   PGTG.NGAY_QD_GIAM NGAY_QUYET_DINH,
   
   MTGQDG.ID MUC_GIAM_ID,
   
   DCQ.ID TOA_QUYET_DINH_ID,
   
   DVHC.ID DIA_PHUONG_ID,
   
   PGTG.NGAY_THA_GIAM_HET_AN NGAY_THA_GIAM_HET_AN,
   
   LLN.ID PHAM_NHAN_ID,
   
   CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
   
   0 AS IS_DELETED,
   
   PGTG.NHAN_XET_TG NHAN_XET,
   
   PGTG.KQCT_PHIEU_GIAM KQCT_PHIEU,
   
   PGTG.KQCT_DS_GIAM KQCT_DANHSACH
  
    FROM QLPN_OLD.PN_GIAM_THOI_HAN PGTG
  
   INNER JOIN QLPN_OLD.PN_LAI_LICH LL
  
      ON PGTG.PN_ID = LL.PN_ID
  
   INNER JOIN QLPN.PN_LAI_LICHS LLN
  
      ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGCH
  
      ON MTGCH.MTG_MA = PGTG.MA_MUC_TG_CHAP_HANH
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGG
  
      ON MTGG.MTG_MA = PGTG.MA_MUC_QD_GIAM_TOA_AN
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGCL
  
      ON MTGCL.MTG_MA = PGTG.MA_MUC_TG_CON_LAI
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGMDN
  
      ON MTGMDN.MTG_MA = PGTG.MA_MUC_DN_GIAM_TG
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGBCA
  
      ON MTGBCA.MTG_MA = PGTG.MA_MUC_DN_GIAM_V26
  
    LEFT JOIN QLPN.DM_MA_THOI_GIANS MTGQDG
  
      ON MTGQDG.MTG_MA = PGTG.MA_MUC_QD_GIAM_TOA_AN
  
    LEFT JOIN QLPN.DM_CO_QUANS DCQ
  
      ON DCQ.CQ_MA = PGTG.MA_CQ_TOA_QD_GIAM
  
    LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DVHC
  
      ON DVHC.DVHC_MA_DVHC = PGTG.MA_DP_TOA_QD_GIAM;
