-- New script in ORCL.
-- Date: Mar 18, 2026
-- Time: 2:09:15 PM
DELETE
FROM
	QLPN.HOAN_THI_HANH_ANS;

INSERT
	INTO
	QLPN.HOAN_THI_HANH_ANS

(PHAM_NHAN_ID,
	SO_QUYET_DINH,
	NGAY_QUYET_DINH,
	TOA_QUYET_DINH_ID,
	DIA_PHUONG_ID,
	LY_DO_HOAN

,
	NGAY_HOAN,
	NOI_CU_TRU,
	NGAY_THI_HANH_AN,
	GHI_CHU,
	CREATION_TIME,
	IS_DELETED)

SELECT
	pll.ID_MOI AS PN_ID,
	SO_QD_HOAN,
	NGAY_QD_HOAN,
	dcq.ID AS MA_CQ_TOA_QD_HOAN,
	ddvhc.ID AS MA_DP_TOA_QD_HOAN

,
	LY_DO_HOAN,
	NGAY_HOAN,
	DC_VE_CU_TRU,
	NGAY_THI_HANH_AN,
	GHI_CHU_HTHA ,
	sysdate AS CREATION_TIME,
	0 AS IS_DELETED
FROM
	QLPN_OLD.PN_HOAN_THI_HANH_AN htha
INNER JOIN (
	SELECT
		lln.ID AS ID_MOI,
		llo.PN_ID AS ID_CU
	FROM
		QLPN_OLD.PN_LAI_LICH llo
	INNER JOIN QLPN.PN_LAI_LICHS lln

ON
		lln.LL_SO_HO_SO_LAN_DAU = llo.SO_HSLD) pll

ON
	htha.PN_ID = pll.ID_CU
LEFT JOIN QLPN.DM_CO_QUANS dcq

ON
	htha.MA_CQ_TOA_QD_HOAN = dcq.CQ_MA
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH ddvhc

ON
	htha.MA_DP_TOA_QD_HOAN = ddvhc.DVHC_MA_DVHC;