delete from QLPN.PN_HSNV_KT_PHAM_NHANS;



INSERT INTO QLPN.PN_HSNV_KT_PHAM_NHANS

(

PN_HSNV_KT_ID,

PN_LAI_LICH_ID,

CREATION_TIME,

IS_DELETED

)

SELECT 

HSNV.PN_ID AS PN_HSNV_KT_ID,

LLN.ID AS PN_LAI_LICH_ID,

CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,

0 AS IS_DELETED

FROM qlpn_old.pn_hsnv_kt HSNV

 INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON HSNV.PN_ID = LL.PN_ID

 INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU;