DELETE FROM QLPN.KHEN_THUONGS;

INSERT INTO QLPN.KHEN_THUONGS
(PHAM_NHAN_ID, NGAY_DE_NGHI, NOI_DE_NGHI, NGAY_KHEN, SO_QUYET_DINH, LY_DO,MA_LY_DO_KHEN_ID,
MA_HINH_THUC_KHEN_ID, HINH_THUC_KHEN
, GHI_CHU, CREATION_TIME, IS_DELETED)
SELECT pll.ID_MOI AS PN_ID,NGAY_DE_NGHI,NOI_DE_NGHI,NGAY_KHEN, SO_QD_KHEN, LY_DO_KHEN, dldk.ID AS MA_LY_DO_KT
, dhtkt.ID AS MA_HINH_THUC_KT, HINH_THUC_KHEN, GHI_CHU, sysdate as CREATION_TIME,0 as IS_DELETED
FROM QLPN_OLD.PN_KHEN_THUONG pkt 
LEFT JOIN (SELECT lln.ID AS ID_MOI
, llo.PN_ID AS ID_CU
FROM QLPN_OLD.PN_LAI_LICH llo
LEFT JOIN QLPN.PN_LAI_LICHS lln
ON lln.LL_SO_HO_SO_LAN_DAU = llo.SO_HSLD) pll
ON pkt.PN_ID = pll.ID_CU 
LEFT JOIN QLPN.DM_LY_DO_KHENS dldk 
ON pkt.MA_LY_DO_KT = dldk.LDK_MA
LEFT JOIN QLPN.DM_HINH_THUC_KHEN_THUONGS dhtkt
ON pkt.MA_HINH_THUC_KT = dhtkt.HTKT_MA