delete from qlpn.PN_SUC_KHOES;

insert into qlpn.PN_SUC_KHOES
(
SK_LOAI_PHIEU,
SK_NGAY_KHAM,
SK_BAC_SI,
PN_LAI_LICH_ID,
CREATION_TIME,
IS_DELETED
)
select 
SKBT.GIAY_XET_NGHIEM_SO SK_LOAI_PHIEU,
SKBT.NGAY_KHAM SK_NGAY_KHAM,
SKBT.BAC_SY_KHAM SK_BAC_SI,
LLN.ID PN_LAI_LICH_ID,
CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
0 AS IS_DELETED
FROM QLPN_OLD.PN_SUC_KHOE_BENH_TAT SKBT
 INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON SKBT.PN_ID = LL.PN_ID
 INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU;
 